def calculate_rotation(current_orientation, target_orientation):
    """
    Calculates the required rotation to move from the current orientation
    to the target orientation.
    """
    # This function was adapted from suggestions generated by Gemini

    # Calculate the difference for each axis (x, y, z) separately.
    # Logic: correction = target - current
    x_correction = target_orientation[0] - current_orientation[0]
    y_correction = target_orientation[1] - current_orientation[1]
    z_correction = target_orientation[2] - current_orientation[2]

    return (x_correction, y_correction, z_correction)