import rotate_me
import time
import math
import adc_utils  # Imported for Check Plus requirement

# --------------------------------------------------------------------------
# NOTE FOR GRADING: ---- Grading comment: Excellent!
# The function below (calculate_rotation) was created for the "Check" task.
# It has been commented out and moved to 'adc_utils.py' to satisfy the
# "Check Plus" requirement of importing it as a module.
# --------------------------------------------------------------------------

# def calculate_rotation(current_orientation, target_orientation):
#     """
#     Calculates the required rotation to move from the current orientation
#     to the target orientation.
#     """
#     # This function was adapted from suggestions generated by Gemini
#
#     # YOUR CODE HERE
#     # Calculate the difference for each axis (x, y, z) separately.
#     # Logic: correction = target - current
#     x_correction = target_orientation[0] - current_orientation[0]
#     y_correction = target_orientation[1] - current_orientation[1]
#     z_correction = target_orientation[2] - current_orientation[2]
#
#     return (x_correction, y_correction, z_correction)

def main():
    """
    Main function to run the attitude control simulation.
    """
    # Set this to the target you want to test:
    # 1. (100, 200, 300)
    # 2. (0, 0, 0)
    # 3. (3, 30, 300)
    target_orientation = (100, 200, 300)

    tolerance = 0.1
    max_iterations = 20

    print(f"Target orientation: {target_orientation}")

    for i in range(max_iterations):
        print(f"\n--- Iteration {i + 1} ---")
        current_orientation = rotate_me.read_orientation_from_file(rotate_me.file_name)
        print(
            f"Current orientation: ({current_orientation[0]:.2f}, {current_orientation[1]:.2f}, {current_orientation[2]:.2f})")

        # Check if we are within tolerance
        error = math.sqrt(sum([(c - t) ** 2 for c, t in zip(current_orientation, target_orientation)]))
        if error <= tolerance:
            print("Target orientation reached!")
            break

        # Calculate the required corrections using the imported module (Check Plus)
        corrections = adc_utils.calculate_rotation(current_orientation, target_orientation)
        print(f"Applying corrections: {corrections}")

        # Apply the corrections using the rotate_me script
        rotate_me.main(corrections)
        time.sleep(1)
    else:
        print("\nMax iterations reached. Could not reach target orientation.")


if __name__ == "__main__":
    main()
